apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: globomantics-gitops
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/CodeWithPraveen/ps-implementing-gitops.git