apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: globomantics-staging
  name: globomantics-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "create", "update", "delete"] 